site_name: Notebook
theme:
  name: material
  language: zh

plugins:
  - search
  - encryptcontent:
      title_prefix: "[LOCK] "
      summary: "此页面已加密。请输入口令解密。"
      placeholder: "输入口令（可用助记词）"
      decryption_failure_message: "口令不正确"
      password_inventory:
        private: 
